In [2]:
from langchain_community.document_loaders import TextLoader
from langchain_text_splitters import CharacterTextSplitter
from langchain_openai import OpenAIEmbeddings

In [3]:
from dotenv import load_dotenv

load_dotenv()

True

In [4]:
import pandas as pd

books = pd.read_csv("books_cleaned.csv")

In [5]:
books

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0,Gilead,9780002005883 A NOVEL THAT READERS and critics...
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0,Spider's Web: A Novel,9780002261982 A new 'Christie for Christmas' -...
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0,Rage of angels,"9780006178736 A memorable, mesmerizing heroine..."
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,33684.0,The Four Loves,9780006280897 Lewis' work on the nature of lov...
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,37569.0,The Problem of Pain,"9780006280934 ""In The Problem of Pain, C.S. Le..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5192,9788172235222,8172235224,Mistaken Identity,Nayantara Sahgal,Indic fiction (English),http://books.google.com/books/content?id=q-tKP...,On A Train Journey Home To North India After L...,2003.0,2.93,324.0,0.0,Mistaken Identity,9788172235222 On A Train Journey Home To North...
5193,9788173031014,8173031010,Journey to the East,Hermann Hesse,Adventure stories,http://books.google.com/books/content?id=rq6JP...,This book tells the tale of a man who goes on ...,2002.0,3.70,175.0,24.0,Journey to the East,9788173031014 This book tells the tale of a ma...
5194,9788179921623,817992162X,The Monk Who Sold His Ferrari: A Fable About F...,Robin Sharma,Health & Fitness,http://books.google.com/books/content?id=c_7mf...,"Wisdom to Create a Life of Passion, Purpose, a...",2003.0,3.82,198.0,1568.0,The Monk Who Sold His Ferrari: A Fable About F...,9788179921623 Wisdom to Create a Life of Passi...
5195,9788185300535,8185300534,I Am that,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JP...,This collection of the timeless teachings of o...,1999.0,4.51,531.0,104.0,I Am that: Talks with Sri Nisargadatta Maharaj,9788185300535 This collection of the timeless ...
5196,9789027712059,9027712050,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,0.00,210.0,0.0,The Berlin Phenomenology,9789027712059 Since the three volume edition o...

In [6]:
books["tagged_description"].head()

0    9780002005883 A NOVEL THAT READERS and critics...
1    9780002261982 A new 'Christie for Christmas' -...
2    9780006178736 A memorable, mesmerizing heroine...
3    9780006280897 Lewis' work on the nature of lov...
4    9780006280934 "In The Problem of Pain, C.S. Le...
Name: tagged_description, dtype: object

In [7]:
books["tagged_description"].to_csv("tagged_description.txt", sep=' ', index=False, header=False)
books["tagged_description"]

0       9780002005883 A NOVEL THAT READERS and critics...
1       9780002261982 A new 'Christie for Christmas' -...
2       9780006178736 A memorable, mesmerizing heroine...
3       9780006280897 Lewis' work on the nature of lov...
4       9780006280934 "In The Problem of Pain, C.S. Le...
                              ...
5192    9788172235222 On A Train Journey Home To North...
5193    9788173031014 This book tells the tale of a ma...
5194    9788179921623 Wisdom to Create a Life of Passi...
5195    9788185300535 This collection of the timeless ...
5196    9789027712059 Since the three volume edition o...
Name: tagged_description, Length: 5197, dtype: object

In [8]:
raw_documents = TextLoader("tagged_description.txt").load()
text_splitter = CharacterTextSplitter(chunk_size=0, chunk_overlap=0, separator="\n")
documents = text_splitter.split_documents(raw_documents)

Created a chunk of size 1170, which is longer than the specified 0
Created a chunk of size 1216, which is longer than the specified 0
Created a chunk of size 375, which is longer than the specified 0
Created a chunk of size 311, which is longer than the specified 0
Created a chunk of size 483, which is longer than the specified 0
Created a chunk of size 484, which is longer than the specified 0
Created a chunk of size 962, which is longer than the specified 0
Created a chunk of size 190, which is longer than the specified 0
Created a chunk of size 845, which is longer than the specified 0
Created a chunk of size 296, which is longer than the specified 0
Created a chunk of size 197, which is longer than the specified 0
Created a chunk of size 881, which is longer than the specified 0
Created a chunk of size 1090, which is longer than the specified 0
Created a chunk of size 1191, which is longer than the specified 0
Created a chunk of size 306, which is longer than the specified 0
Created a chunk of size 272, which is longer than the specified 0
Created a chunk of size 213, which is longer than the specified 0
Created a chunk of size 216, which is longer than the specified 0
Created a chunk of size 515, which is longer than the specified 0
Created a chunk of size 754, which is longer than the specified 0
Created a chunk of size 390, which is longer than the specified 0
Created a chunk of size 265, which is longer than the specified 0
Created a chunk of size 253, which is longer than the specified 0
Created a chunk of size 308, which is longer than the specified 0
Created a chunk of size 730, which is longer than the specified 0
Created a chunk of size 723, which is longer than the specified 0
Created a chunk of size 258, which is longer than the specified 0
Created a chunk of size 475, which is longer than the specified 0
Created a chunk of size 272, which is longer than the specified 0
Created a chunk of size 1267, which is longer than the specified 0
Created a chunk of size 683, which is longer than the specified 0
Created a chunk of size 243, which is longer than the specified 0
Created a chunk of size 555, which is longer than the specified 0
Created a chunk of size 523, which is longer than the specified 0
Created a chunk of size 282, which is longer than the specified 0
Created a chunk of size 789, which is longer than the specified 0
Created a chunk of size 566, which is longer than the specified 0
Created a chunk of size 525, which is longer than the specified 0
Created a chunk of size 179, which is longer than the specified 0
Created a chunk of size 299, which is longer than the specified 0
Created a chunk of size 535, which is longer than the specified 0
Created a chunk of size 561, which is longer than the specified 0
Created a chunk of size 565, which is longer than the specified 0
Created a chunk of size 385, which is longer than the specified 0
Created a chunk of size 412, which is longer than the specified 0
Created a chunk of size 463, which is longer than the specified 0
Created a chunk of size 597, which is longer than the specified 0
Created a chunk of size 478, which is longer than the specified 0
Created a chunk of size 461, which is longer than the specified 0
Created a chunk of size 259, which is longer than the specified 0
Created a chunk of size 306, which is longer than the specified 0
Created a chunk of size 616, which is longer than the specified 0
Created a chunk of size 421, which is longer than the specified 0
Created a chunk of size 889, which is longer than the specified 0
Created a chunk of size 695, which is longer than the specified 0
Created a chunk of size 304, which is longer than the specified 0
Created a chunk of size 219, which is longer than the specified 0
Created a chunk of size 277, which is longer than the specified 0
Created a chunk of size 2010, which is longer than the specified 0
Created a chunk of size 175, which is longer than the specified 0
Created a chunk of size 481, which is longer than the specified 0
Created a chunk of size 302, which is longer than the specified 0
Created a chunk of size 522, which is longer than the specified 0
Created a chunk of size 649, which is longer than the specified 0
Created a chunk of size 778, which is longer than the specified 0
Created a chunk of size 167, which is longer than the specified 0
Created a chunk of size 688, which is longer than the specified 0
Created a chunk of size 550, which is longer than the specified 0
Created a chunk of size 1225, which is longer than the specified 0
Created a chunk of size 408, which is longer than the specified 0
Created a chunk of size 1186, which is longer than the specified 0
Created a chunk of size 1216, which is longer than the specified 0
Created a chunk of size 1193, which is longer than the specified 0
Created a chunk of size 1059, which is longer than the specified 0
Created a chunk of size 246, which is longer than the specified 0
Created a chunk of size 690, which is longer than the specified 0
Created a chunk of size 878, which is longer than the specified 0
Created a chunk of size 286, which is longer than the specified 0
Created a chunk of size 768, which is longer than the specified 0
Created a chunk of size 389, which is longer than the specified 0
Created a chunk of size 419, which is longer than the specified 0
Created a chunk of size 210, which is longer than the specified 0
Created a chunk of size 209, which is longer than the specified 0
Created a chunk of size 725, which is longer than the specified 0
Created a chunk of size 211, which is longer than the specified 0
Created a chunk of size 165, which is longer than the specified 0
Created a chunk of size 528, which is longer than the specified 0
Created a chunk of size 523, which is longer than the specified 0
Created a chunk of size 216, which is longer than the specified 0
Created a chunk of size 340, which is longer than the specified 0
Created a chunk of size 901, which is longer than the specified 0
Created a chunk of size 1272, which is longer than the specified 0
Created a chunk of size 560, which is longer than the specified 0
Created a chunk of size 1637, which is longer than the specified 0
Created a chunk of size 438, which is longer than the specified 0
Created a chunk of size 251, which is longer than the specified 0
Created a chunk of size 779, which is longer than the specified 0
Created a chunk of size 718, which is longer than the specified 0
Created a chunk of size 516, which is longer than the specified 0
Created a chunk of size 960, which is longer than the specified 0
Created a chunk of size 200, which is longer than the specified 0
Created a chunk of size 1132, which is longer than the specified 0
Created a chunk of size 170, which is longer than the specified 0
Created a chunk of size 1325, which is longer than the specified 0
Created a chunk of size 853, which is longer than the specified 0
Created a chunk of size 274, which is longer than the specified 0
Created a chunk of size 801, which is longer than the specified 0
Created a chunk of size 1121, which is longer than the specified 0
Created a chunk of size 838, which is longer than the specified 0
Created a chunk of size 262, which is longer than the specified 0
Created a chunk of size 237, which is longer than the specified 0
Created a chunk of size 734, which is longer than the specified 0
Created a chunk of size 1195, which is longer than the specified 0
Created a chunk of size 712, which is longer than the specified 0
Created a chunk of size 775, which is longer than the specified 0
Created a chunk of size 280, which is longer than the specified 0
Created a chunk of size 309, which is longer than the specified 0
Created a chunk of size 358, which is longer than the specified 0
Created a chunk of size 768, which is longer than the specified 0
Created a chunk of size 767, which is longer than the specified 0
Created a chunk of size 718, which is longer than the specified 0
Created a chunk of size 2012, which is longer than the specified 0
Created a chunk of size 310, which is longer than the specified 0
Created a chunk of size 1288, which is longer than the specified 0
Created a chunk of size 1231, which is longer than the specified 0
Created a chunk of size 729, which is longer than the specified 0
Created a chunk of size 750, which is longer than the specified 0
Created a chunk of size 447, which is longer than the specified 0
Created a chunk of size 1242, which is longer than the specified 0
Created a chunk of size 311, which is longer than the specified 0
Created a chunk of size 914, which is longer than the specified 0
Created a chunk of size 306, which is longer than the specified 0
Created a chunk of size 846, which is longer than the specified 0
Created a chunk of size 1128, which is longer than the specified 0
Created a chunk of size 1075, which is longer than the specified 0
Created a chunk of size 1320, which is longer than the specified 0
Created a chunk of size 363, which is longer than the specified 0
Created a chunk of size 2834, which is longer than the specified 0
Created a chunk of size 237, which is longer than the specified 0
Created a chunk of size 242, which is longer than the specified 0
Created a chunk of size 173, which is longer than the specified 0
Created a chunk of size 206, which is longer than the specified 0
Created a chunk of size 572, which is longer than the specified 0
Created a chunk of size 208, which is longer than the specified 0
Created a chunk of size 367, which is longer than the specified 0
Created a chunk of size 1143, which is longer than the specified 0
Created a chunk of size 1006, which is longer than the specified 0
Created a chunk of size 715, which is longer than the specified 0
Created a chunk of size 712, which is longer than the specified 0
Created a chunk of size 2510, which is longer than the specified 0
Created a chunk of size 956, which is longer than the specified 0
Created a chunk of size 309, which is longer than the specified 0
Created a chunk of size 351, which is longer than the specified 0
Created a chunk of size 641, which is longer than the specified 0
Created a chunk of size 405, which is longer than the specified 0
Created a chunk of size 525, which is longer than the specified 0
Created a chunk of size 795, which is longer than the specified 0
Created a chunk of size 167, which is longer than the specified 0
Created a chunk of size 391, which is longer than the specified 0
Created a chunk of size 256, which is longer than the specified 0
Created a chunk of size 1424, which is longer than the specified 0
Created a chunk of size 1085, which is longer than the specified 0
Created a chunk of size 1146, which is longer than the specified 0
Created a chunk of size 1268, which is longer than the specified 0
Created a chunk of size 790, which is longer than the specified 0
Created a chunk of size 297, which is longer than the specified 0
Created a chunk of size 1088, which is longer than the specified 0
Created a chunk of size 874, which is longer than the specified 0
Created a chunk of size 256, which is longer than the specified 0
Created a chunk of size 876, which is longer than the specified 0
Created a chunk of size 808, which is longer than the specified 0
Created a chunk of size 1814, which is longer than the specified 0
Created a chunk of size 1830, which is longer than the specified 0
Created a chunk of size 1064, which is longer than the specified 0
Created a chunk of size 955, which is longer than the specified 0
Created a chunk of size 1182, which is longer than the specified 0
Created a chunk of size 283, which is longer than the specified 0
Created a chunk of size 283, which is longer than the specified 0
Created a chunk of size 288, which is longer than the specified 0
Created a chunk of size 1286, which is longer than the specified 0
Created a chunk of size 1644, which is longer than the specified 0
Created a chunk of size 759, which is longer than the specified 0
Created a chunk of size 1932, which is longer than the specified 0
Created a chunk of size 874, which is longer than the specified 0
Created a chunk of size 2008, which is longer than the specified 0
Created a chunk of size 2285, which is longer than the specified 0
Created a chunk of size 175, which is longer than the specified 0
Created a chunk of size 1003, which is longer than the specified 0
Created a chunk of size 579, which is longer than the specified 0
Created a chunk of size 290, which is longer than the specified 0
Created a chunk of size 257, which is longer than the specified 0
Created a chunk of size 1144, which is longer than the specified 0
Created a chunk of size 559, which is longer than the specified 0
Created a chunk of size 1143, which is longer than the specified 0
Created a chunk of size 245, which is longer than the specified 0
Created a chunk of size 1088, which is longer than the specified 0
Created a chunk of size 1483, which is longer than the specified 0
Created a chunk of size 223, which is longer than the specified 0
Created a chunk of size 1137, which is longer than the specified 0
Created a chunk of size 724, which is longer than the specified 0
Created a chunk of size 668, which is longer than the specified 0
Created a chunk of size 767, which is longer than the specified 0
Created a chunk of size 608, which is longer than the specified 0
Created a chunk of size 572, which is longer than the specified 0
Created a chunk of size 967, which is longer than the specified 0
Created a chunk of size 859, which is longer than the specified 0
Created a chunk of size 1034, which is longer than the specified 0
Created a chunk of size 191, which is longer than the specified 0
Created a chunk of size 369, which is longer than the specified 0
Created a chunk of size 497, which is longer than the specified 0
Created a chunk of size 652, which is longer than the specified 0
Created a chunk of size 350, which is longer than the specified 0
Created a chunk of size 735, which is longer than the specified 0
Created a chunk of size 527, which is longer than the specified 0
Created a chunk of size 1017, which is longer than the specified 0
Created a chunk of size 972, which is longer than the specified 0
Created a chunk of size 206, which is longer than the specified 0
Created a chunk of size 690, which is longer than the specified 0
Created a chunk of size 546, which is longer than the specified 0
Created a chunk of size 244, which is longer than the specified 0
Created a chunk of size 209, which is longer than the specified 0
Created a chunk of size 378, which is longer than the specified 0
Created a chunk of size 933, which is longer than the specified 0
Created a chunk of size 564, which is longer than the specified 0
Created a chunk of size 856, which is longer than the specified 0
Created a chunk of size 717, which is longer than the specified 0
Created a chunk of size 749, which is longer than the specified 0
Created a chunk of size 714, which is longer than the specified 0
Created a chunk of size 326, which is longer than the specified 0
Created a chunk of size 243, which is longer than the specified 0
Created a chunk of size 1090, which is longer than the specified 0
Created a chunk of size 725, which is longer than the specified 0
Created a chunk of size 247, which is longer than the specified 0
Created a chunk of size 229, which is longer than the specified 0
Created a chunk of size 706, which is longer than the specified 0
Created a chunk of size 1914, which is longer than the specified 0
Created a chunk of size 397, which is longer than the specified 0
Created a chunk of size 487, which is longer than the specified 0
Created a chunk of size 622, which is longer than the specified 0
Created a chunk of size 561, which is longer than the specified 0
Created a chunk of size 558, which is longer than the specified 0
Created a chunk of size 388, which is longer than the specified 0
Created a chunk of size 231, which is longer than the specified 0
Created a chunk of size 427, which is longer than the specified 0
Created a chunk of size 418, which is longer than the specified 0
Created a chunk of size 286, which is longer than the specified 0
Created a chunk of size 168, which is longer than the specified 0
Created a chunk of size 626, which is longer than the specified 0
Created a chunk of size 2616, which is longer than the specified 0
Created a chunk of size 1580, which is longer than the specified 0
Created a chunk of size 391, which is longer than the specified 0
Created a chunk of size 996, which is longer than the specified 0
Created a chunk of size 849, which is longer than the specified 0
Created a chunk of size 265, which is longer than the specified 0
Created a chunk of size 338, which is longer than the specified 0
Created a chunk of size 1530, which is longer than the specified 0
Created a chunk of size 215, which is longer than the specified 0
Created a chunk of size 291, which is longer than the specified 0
Created a chunk of size 2032, which is longer than the specified 0
Created a chunk of size 398, which is longer than the specified 0
Created a chunk of size 1619, which is longer than the specified 0
Created a chunk of size 700, which is longer than the specified 0
Created a chunk of size 824, which is longer than the specified 0
Created a chunk of size 356, which is longer than the specified 0
Created a chunk of size 843, which is longer than the specified 0
Created a chunk of size 1191, which is longer than the specified 0
Created a chunk of size 197, which is longer than the specified 0
Created a chunk of size 510, which is longer than the specified 0
Created a chunk of size 665, which is longer than the specified 0
Created a chunk of size 1284, which is longer than the specified 0
Created a chunk of size 262, which is longer than the specified 0
Created a chunk of size 244, which is longer than the specified 0
Created a chunk of size 217, which is longer than the specified 0
Created a chunk of size 200, which is longer than the specified 0
Created a chunk of size 1268, which is longer than the specified 0
Created a chunk of size 1277, which is longer than the specified 0
Created a chunk of size 200, which is longer than the specified 0
Created a chunk of size 1058, which is longer than the specified 0
Created a chunk of size 380, which is longer than the specified 0
Created a chunk of size 271, which is longer than the specified 0
Created a chunk of size 179, which is longer than the specified 0
Created a chunk of size 227, which is longer than the specified 0
Created a chunk of size 224, which is longer than the specified 0
Created a chunk of size 784, which is longer than the specified 0
Created a chunk of size 971, which is longer than the specified 0
Created a chunk of size 615, which is longer than the specified 0
Created a chunk of size 165, which is longer than the specified 0
Created a chunk of size 759, which is longer than the specified 0
Created a chunk of size 291, which is longer than the specified 0
Created a chunk of size 247, which is longer than the specified 0
Created a chunk of size 965, which is longer than the specified 0
Created a chunk of size 234, which is longer than the specified 0
Created a chunk of size 845, which is longer than the specified 0
Created a chunk of size 788, which is longer than the specified 0
Created a chunk of size 650, which is longer than the specified 0
Created a chunk of size 986, which is longer than the specified 0
Created a chunk of size 799, which is longer than the specified 0
Created a chunk of size 195, which is longer than the specified 0
Created a chunk of size 1163, which is longer than the specified 0
Created a chunk of size 255, which is longer than the specified 0
Created a chunk of size 203, which is longer than the specified 0
Created a chunk of size 1058, which is longer than the specified 0

In [9]:
documents[1]

Document(metadata={'source': 'tagged_description.txt'}, page_content='"9780002261982 A new \'Christie for Christmas\' -- a full-length novel adapted from her acclaimed play by Charles Osborne Following BLACK COFFEE and THE UNEXPECTED GUEST comes the final Agatha Christie play novelisation, bringing her superb storytelling to a new legion of fans. Clarissa, the wife of a Foreign Office diplomat, is given to daydreaming. \'Supposing I were to come down one morning and find a dead body in the library, what should I do?\' she muses. Clarissa has her chance to find out when she discovers a body in the drawing-room of her house in Kent. Desperate to dispose of the body before her husband comes home with an important foreign politician, Clarissa persuades her three house guests to become accessories and accomplices. It seems that the murdered man was not unknown to certain members of the house party (but which ones?), and the search begins for the murderer and the motive, while at the same time trying to persuade a police inspector that there has been no murder at all... SPIDER\'S WEB was written in 1954 specifically for Margaret Lockwood and opened first at the Theatre Royal Nottingham before moving to the Savoy Theatre in London on 14 December 1954. With THE MOUSETRAP and WI"')

In [10]:
import os

In [11]:
pip install langchain-huggingface

Requirement already satisfied: langchain-huggingface in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (0.1.2)
Requirement already satisfied: huggingface-hub>=0.23.0 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from langchain-huggingface) (0.29.3)
Requirement already satisfied: langchain-core<0.4.0,>=0.3.15 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from langchain-huggingface) (0.3.49)
Requirement already satisfied: sentence-transformers>=2.6.0 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from langchain-huggingface) (4.0.1)
Requirement already satisfied: tokenizers>=0.19.1 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from langchain-huggingface) (0.21.1)
Requirement already satisfied: transformers>=4.39.0 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from langchain-huggingface) (4.50.3)
Requirement already satisfied: filelock in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from huggingface-hub>=0.23.0->langchain-huggingface) (3.18.0)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from huggingface-hub>=0.23.0->langchain-huggingface) (2025.3.0)
Requirement already satisfied: packaging>=20.9 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from huggingface-hub>=0.23.0->langchain-huggingface) (24.2)
Requirement already satisfied: pyyaml>=5.1 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from huggingface-hub>=0.23.0->langchain-huggingface) (6.0.2)
Requirement already satisfied: requests in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from huggingface-hub>=0.23.0->langchain-huggingface) (2.32.3)
Requirement already satisfied: tqdm>=4.42.1 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from huggingface-hub>=0.23.0->langchain-huggingface) (4.67.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from huggingface-hub>=0.23.0->langchain-huggingface) (4.13.0)
Requirement already satisfied: langsmith<0.4,>=0.1.125 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from langchain-core<0.4.0,>=0.3.15->langchain-huggingface) (0.3.19)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from langchain-core<0.4.0,>=0.3.15->langchain-huggingface) (9.0.0)
Requirement already satisfied: jsonpatch<2.0,>=1.33 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from langchain-core<0.4.0,>=0.3.15->langchain-huggingface) (1.33)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from langchain-core<0.4.0,>=0.3.15->langchain-huggingface) (2.11.0)
Requirement already satisfied: torch>=1.11.0 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from sentence-transformers>=2.6.0->langchain-huggingface) (2.6.0+cu126)
Requirement already satisfied: scikit-learn in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from sentence-transformers>=2.6.0->langchain-huggingface) (1.6.1)
Requirement already satisfied: scipy in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from sentence-transformers>=2.6.0->langchain-huggingface) (1.15.2)
Requirement already satisfied: Pillow in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from sentence-transformers>=2.6.0->langchain-huggingface) (11.1.0)
Requirement already satisfied: numpy>=1.17 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from transformers>=4.39.0->langchain-huggingface) (2.2.4)
Requirement already satisfied: regex!=2019.12.17 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from transformers>=4.39.0->langchain-huggingface) (2024.11.6)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from transformers>=4.39.0->langchain-huggingface) (0.5.3)
Requirement already satisfied: jsonpointer>=1.9 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jsonpatch<2.0,>=1.33->langchain-core<0.4.0,>=0.3.15->langchain-huggingface) (3.0.0)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from langsmith<0.4,>=0.1.125->langchain-core<0.4.0,>=0.3.15->langchain-huggingface) (0.28.1)
Requirement already satisfied: orjson<4.0.0,>=3.9.14 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from langsmith<0.4,>=0.1.125->langchain-core<0.4.0,>=0.3.15->langchain-huggingface) (3.10.16)
Requirement already satisfied: requests-toolbelt<2.0.0,>=1.0.0 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from langsmith<0.4,>=0.1.125->langchain-core<0.4.0,>=0.3.15->langchain-huggingface) (1.0.0)
Requirement already satisfied: zstandard<0.24.0,>=0.23.0 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from langsmith<0.4,>=0.1.125->langchain-core<0.4.0,>=0.3.15->langchain-huggingface) (0.23.0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<0.4.0,>=0.3.15->langchain-huggingface) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.0 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<0.4.0,>=0.3.15->langchain-huggingface) (2.33.0)
Requirement already satisfied: typing-inspection>=0.4.0 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<0.4.0,>=0.3.15->langchain-huggingface) (0.4.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from requests->huggingface-hub>=0.23.0->langchain-huggingface) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from requests->huggingface-hub>=0.23.0->langchain-huggingface) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from requests->huggingface-hub>=0.23.0->langchain-huggingface) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from requests->huggingface-hub>=0.23.0->langchain-huggingface) (2025.1.31)
Requirement already satisfied: networkx in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from torch>=1.11.0->sentence-transformers>=2.6.0->langchain-huggingface) (3.4.2)
Requirement already satisfied: jinja2 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from torch>=1.11.0->sentence-transformers>=2.6.0->langchain-huggingface) (3.1.6)
Requirement already satisfied: setuptools in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from torch>=1.11.0->sentence-transformers>=2.6.0->langchain-huggingface) (78.1.0)
Requirement already satisfied: sympy==1.13.1 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from torch>=1.11.0->sentence-transformers>=2.6.0->langchain-huggingface) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from sympy==1.13.1->torch>=1.11.0->sentence-transformers>=2.6.0->langchain-huggingface) (1.3.0)
Requirement already satisfied: colorama in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from tqdm>=4.42.1->huggingface-hub>=0.23.0->langchain-huggingface) (0.4.6)
Requirement already satisfied: joblib>=1.2.0 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from scikit-learn->sentence-transformers>=2.6.0->langchain-huggingface) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from scikit-learn->sentence-transformers>=2.6.0->langchain-huggingface) (3.6.0)
Requirement already satisfied: anyio in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from httpx<1,>=0.23.0->langsmith<0.4,>=0.1.125->langchain-core<0.4.0,>=0.3.15->langchain-huggingface) (4.9.0)
Requirement already satisfied: httpcore==1.* in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from httpx<1,>=0.23.0->langsmith<0.4,>=0.1.125->langchain-core<0.4.0,>=0.3.15->langchain-huggingface) (1.0.7)
Requirement already satisfied: h11<0.15,>=0.13 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith<0.4,>=0.1.125->langchain-core<0.4.0,>=0.3.15->langchain-huggingface) (0.14.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jinja2->torch>=1.11.0->sentence-transformers>=2.6.0->langchain-huggingface) (3.0.2)
Requirement already satisfied: sniffio>=1.1 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from anyio->httpx<1,>=0.23.0->langsmith<0.4,>=0.1.125->langchain-core<0.4.0,>=0.3.15->langchain-huggingface) (1.3.1)
Note: you may need to restart the kernel to use updated packages.

In [12]:
from langchain_huggingface import HuggingFaceEmbeddings

In [13]:
pip install --upgrade jupyter ipywidgets

Requirement already satisfied: jupyter in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (1.1.1)
Requirement already satisfied: ipywidgets in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (8.1.5)
Requirement already satisfied: notebook in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jupyter) (7.3.3)
Requirement already satisfied: jupyter-console in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jupyter) (6.6.3)
Requirement already satisfied: nbconvert in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jupyter) (7.16.6)
Requirement already satisfied: ipykernel in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jupyter) (6.29.5)
Requirement already satisfied: jupyterlab in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jupyter) (4.3.6)
Requirement already satisfied: comm>=0.1.3 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from ipywidgets) (0.2.2)
Requirement already satisfied: ipython>=6.1.0 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from ipywidgets) (9.0.2)
Requirement already satisfied: traitlets>=4.3.1 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from ipywidgets) (5.14.3)
Requirement already satisfied: widgetsnbextension~=4.0.12 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from ipywidgets) (4.0.13)
Requirement already satisfied: jupyterlab-widgets~=3.0.12 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from ipywidgets) (3.0.13)
Requirement already satisfied: colorama in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.4.6)
Requirement already satisfied: decorator in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from ipython>=6.1.0->ipywidgets) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from ipython>=6.1.0->ipywidgets) (1.1.1)
Requirement already satisfied: jedi>=0.16 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.19.2)
Requirement already satisfied: matplotlib-inline in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.1.7)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from ipython>=6.1.0->ipywidgets) (3.0.50)
Requirement already satisfied: pygments>=2.4.0 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from ipython>=6.1.0->ipywidgets) (2.19.1)
Requirement already satisfied: stack_data in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.6.3)
Requirement already satisfied: debugpy>=1.6.5 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from ipykernel->jupyter) (1.8.13)
Requirement already satisfied: jupyter-client>=6.1.12 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from ipykernel->jupyter) (8.6.3)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from ipykernel->jupyter) (5.7.2)
Requirement already satisfied: nest-asyncio in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from ipykernel->jupyter) (1.6.0)
Requirement already satisfied: packaging in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from ipykernel->jupyter) (24.2)
Requirement already satisfied: psutil in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from ipykernel->jupyter) (7.0.0)
Requirement already satisfied: pyzmq>=24 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from ipykernel->jupyter) (26.3.0)
Requirement already satisfied: tornado>=6.1 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from ipykernel->jupyter) (6.4.2)
Requirement already satisfied: async-lru>=1.0.0 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jupyterlab->jupyter) (2.0.5)
Requirement already satisfied: httpx>=0.25.0 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jupyterlab->jupyter) (0.28.1)
Requirement already satisfied: jinja2>=3.0.3 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jupyterlab->jupyter) (3.1.6)
Requirement already satisfied: jupyter-lsp>=2.0.0 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jupyterlab->jupyter) (2.2.5)
Requirement already satisfied: jupyter-server<3,>=2.4.0 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jupyterlab->jupyter) (2.15.0)
Requirement already satisfied: jupyterlab-server<3,>=2.27.1 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jupyterlab->jupyter) (2.27.3)
Requirement already satisfied: notebook-shim>=0.2 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jupyterlab->jupyter) (0.2.4)
Requirement already satisfied: setuptools>=40.8.0 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jupyterlab->jupyter) (78.1.0)
Requirement already satisfied: beautifulsoup4 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from nbconvert->jupyter) (4.13.3)
Requirement already satisfied: bleach!=5.0.0 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from bleach[css]!=5.0.0->nbconvert->jupyter) (6.2.0)
Requirement already satisfied: defusedxml in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from nbconvert->jupyter) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from nbconvert->jupyter) (0.3.0)
Requirement already satisfied: markupsafe>=2.0 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from nbconvert->jupyter) (3.0.2)
Requirement already satisfied: mistune<4,>=2.0.3 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from nbconvert->jupyter) (3.1.3)
Requirement already satisfied: nbclient>=0.5.0 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from nbconvert->jupyter) (0.10.2)
Requirement already satisfied: nbformat>=5.7 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from nbconvert->jupyter) (5.10.4)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from nbconvert->jupyter) (1.5.1)
Requirement already satisfied: webencodings in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from bleach!=5.0.0->bleach[css]!=5.0.0->nbconvert->jupyter) (0.5.1)
Requirement already satisfied: tinycss2<1.5,>=1.1.0 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from bleach[css]!=5.0.0->nbconvert->jupyter) (1.4.0)
Requirement already satisfied: anyio in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from httpx>=0.25.0->jupyterlab->jupyter) (4.9.0)
Requirement already satisfied: certifi in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from httpx>=0.25.0->jupyterlab->jupyter) (2025.1.31)
Requirement already satisfied: httpcore==1.* in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from httpx>=0.25.0->jupyterlab->jupyter) (1.0.7)
Requirement already satisfied: idna in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from httpx>=0.25.0->jupyterlab->jupyter) (3.10)
Requirement already satisfied: h11<0.15,>=0.13 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from httpcore==1.*->httpx>=0.25.0->jupyterlab->jupyter) (0.14.0)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jedi>=0.16->ipython>=6.1.0->ipywidgets) (0.8.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jupyter-client>=6.1.12->ipykernel->jupyter) (2.9.0.post0)
Requirement already satisfied: platformdirs>=2.5 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel->jupyter) (4.3.7)
Requirement already satisfied: pywin32>=300 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel->jupyter) (310)
Requirement already satisfied: argon2-cffi>=21.1 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (23.1.0)
Requirement already satisfied: jupyter-events>=0.11.0 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.12.0)
Requirement already satisfied: jupyter-server-terminals>=0.4.4 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.5.3)
Requirement already satisfied: overrides>=5.0 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (7.7.0)
Requirement already satisfied: prometheus-client>=0.9 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.21.1)
Requirement already satisfied: pywinpty>=2.0.1 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (2.0.15)
Requirement already satisfied: send2trash>=1.8.2 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.8.3)
Requirement already satisfied: terminado>=0.8.3 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.18.1)
Requirement already satisfied: websocket-client>=1.7 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.8.0)
Requirement already satisfied: babel>=2.10 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (2.17.0)
Requirement already satisfied: json5>=0.9.0 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (0.10.0)
Requirement already satisfied: jsonschema>=4.18.0 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (4.23.0)
Requirement already satisfied: requests>=2.31 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (2.32.3)
Requirement already satisfied: fastjsonschema>=2.15 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from nbformat>=5.7->nbconvert->jupyter) (2.21.1)
Requirement already satisfied: wcwidth in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets) (0.2.13)
Requirement already satisfied: soupsieve>1.2 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from beautifulsoup4->nbconvert->jupyter) (2.6)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from beautifulsoup4->nbconvert->jupyter) (4.13.0)
Requirement already satisfied: executing>=1.2.0 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from stack_data->ipython>=6.1.0->ipywidgets) (2.2.0)
Requirement already satisfied: asttokens>=2.1.0 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from stack_data->ipython>=6.1.0->ipywidgets) (3.0.0)
Requirement already satisfied: pure-eval in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from stack_data->ipython>=6.1.0->ipywidgets) (0.2.3)
Requirement already satisfied: sniffio>=1.1 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from anyio->httpx>=0.25.0->jupyterlab->jupyter) (1.3.1)
Requirement already satisfied: argon2-cffi-bindings in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (21.2.0)
Requirement already satisfied: attrs>=22.2.0 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (25.3.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (2024.10.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (0.36.2)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (0.24.0)
Requirement already satisfied: python-json-logger>=2.0.4 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (3.3.0)
Requirement already satisfied: pyyaml>=5.3 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (6.0.2)
Requirement already satisfied: rfc3339-validator in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.1.4)
Requirement already satisfied: rfc3986-validator>=0.1.1 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.1.1)
Requirement already satisfied: six>=1.5 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from python-dateutil>=2.8.2->jupyter-client>=6.1.12->ipykernel->jupyter) (1.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (3.4.1)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (2.3.0)
Requirement already satisfied: fqdn in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.5.1)
Requirement already satisfied: isoduration in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (20.11.0)
Requirement already satisfied: jsonpointer>1.13 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (3.0.0)
Requirement already satisfied: uri-template in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.3.0)
Requirement already satisfied: webcolors>=24.6.0 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (24.11.1)
Requirement already satisfied: cffi>=1.0.1 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.17.1)
Requirement already satisfied: pycparser in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (2.22)
Requirement already satisfied: arrow>=0.15.0 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.3.0)
Requirement already satisfied: types-python-dateutil>=2.8.10 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from arrow>=0.15.0->isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (2.9.0.20241206)
Note: you may need to restart the kernel to use updated packages.

In [14]:
embeddings = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")

In [ ]:
import torch

CUDA available: True

In [16]:
from langchain_community.vectorstores import FAISS

In [17]:
pip install --upgrade jupyter ipywidgets

Requirement already satisfied: jupyter in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (1.1.1)
Requirement already satisfied: ipywidgets in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (8.1.5)
Requirement already satisfied: notebook in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jupyter) (7.3.3)
Requirement already satisfied: jupyter-console in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jupyter) (6.6.3)
Requirement already satisfied: nbconvert in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jupyter) (7.16.6)
Requirement already satisfied: ipykernel in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jupyter) (6.29.5)
Requirement already satisfied: jupyterlab in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jupyter) (4.3.6)
Requirement already satisfied: comm>=0.1.3 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from ipywidgets) (0.2.2)
Requirement already satisfied: ipython>=6.1.0 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from ipywidgets) (9.0.2)
Requirement already satisfied: traitlets>=4.3.1 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from ipywidgets) (5.14.3)
Requirement already satisfied: widgetsnbextension~=4.0.12 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from ipywidgets) (4.0.13)
Requirement already satisfied: jupyterlab-widgets~=3.0.12 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from ipywidgets) (3.0.13)
Requirement already satisfied: colorama in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.4.6)
Requirement already satisfied: decorator in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from ipython>=6.1.0->ipywidgets) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from ipython>=6.1.0->ipywidgets) (1.1.1)
Requirement already satisfied: jedi>=0.16 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.19.2)
Requirement already satisfied: matplotlib-inline in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.1.7)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from ipython>=6.1.0->ipywidgets) (3.0.50)
Requirement already satisfied: pygments>=2.4.0 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from ipython>=6.1.0->ipywidgets) (2.19.1)
Requirement already satisfied: stack_data in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.6.3)
Requirement already satisfied: debugpy>=1.6.5 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from ipykernel->jupyter) (1.8.13)
Requirement already satisfied: jupyter-client>=6.1.12 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from ipykernel->jupyter) (8.6.3)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from ipykernel->jupyter) (5.7.2)
Requirement already satisfied: nest-asyncio in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from ipykernel->jupyter) (1.6.0)
Requirement already satisfied: packaging in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from ipykernel->jupyter) (24.2)
Requirement already satisfied: psutil in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from ipykernel->jupyter) (7.0.0)
Requirement already satisfied: pyzmq>=24 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from ipykernel->jupyter) (26.3.0)
Requirement already satisfied: tornado>=6.1 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from ipykernel->jupyter) (6.4.2)
Requirement already satisfied: async-lru>=1.0.0 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jupyterlab->jupyter) (2.0.5)
Requirement already satisfied: httpx>=0.25.0 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jupyterlab->jupyter) (0.28.1)
Requirement already satisfied: jinja2>=3.0.3 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jupyterlab->jupyter) (3.1.6)
Requirement already satisfied: jupyter-lsp>=2.0.0 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jupyterlab->jupyter) (2.2.5)
Requirement already satisfied: jupyter-server<3,>=2.4.0 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jupyterlab->jupyter) (2.15.0)
Requirement already satisfied: jupyterlab-server<3,>=2.27.1 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jupyterlab->jupyter) (2.27.3)
Requirement already satisfied: notebook-shim>=0.2 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jupyterlab->jupyter) (0.2.4)
Requirement already satisfied: setuptools>=40.8.0 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jupyterlab->jupyter) (78.1.0)
Requirement already satisfied: beautifulsoup4 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from nbconvert->jupyter) (4.13.3)
Requirement already satisfied: bleach!=5.0.0 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from bleach[css]!=5.0.0->nbconvert->jupyter) (6.2.0)
Requirement already satisfied: defusedxml in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from nbconvert->jupyter) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from nbconvert->jupyter) (0.3.0)
Requirement already satisfied: markupsafe>=2.0 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from nbconvert->jupyter) (3.0.2)
Requirement already satisfied: mistune<4,>=2.0.3 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from nbconvert->jupyter) (3.1.3)
Requirement already satisfied: nbclient>=0.5.0 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from nbconvert->jupyter) (0.10.2)
Requirement already satisfied: nbformat>=5.7 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from nbconvert->jupyter) (5.10.4)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from nbconvert->jupyter) (1.5.1)
Requirement already satisfied: webencodings in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from bleach!=5.0.0->bleach[css]!=5.0.0->nbconvert->jupyter) (0.5.1)
Requirement already satisfied: tinycss2<1.5,>=1.1.0 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from bleach[css]!=5.0.0->nbconvert->jupyter) (1.4.0)
Requirement already satisfied: anyio in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from httpx>=0.25.0->jupyterlab->jupyter) (4.9.0)
Requirement already satisfied: certifi in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from httpx>=0.25.0->jupyterlab->jupyter) (2025.1.31)
Requirement already satisfied: httpcore==1.* in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from httpx>=0.25.0->jupyterlab->jupyter) (1.0.7)
Requirement already satisfied: idna in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from httpx>=0.25.0->jupyterlab->jupyter) (3.10)
Requirement already satisfied: h11<0.15,>=0.13 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from httpcore==1.*->httpx>=0.25.0->jupyterlab->jupyter) (0.14.0)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jedi>=0.16->ipython>=6.1.0->ipywidgets) (0.8.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jupyter-client>=6.1.12->ipykernel->jupyter) (2.9.0.post0)
Requirement already satisfied: platformdirs>=2.5 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel->jupyter) (4.3.7)
Requirement already satisfied: pywin32>=300 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel->jupyter) (310)
Requirement already satisfied: argon2-cffi>=21.1 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (23.1.0)
Requirement already satisfied: jupyter-events>=0.11.0 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.12.0)
Requirement already satisfied: jupyter-server-terminals>=0.4.4 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.5.3)
Requirement already satisfied: overrides>=5.0 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (7.7.0)
Requirement already satisfied: prometheus-client>=0.9 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.21.1)
Requirement already satisfied: pywinpty>=2.0.1 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (2.0.15)
Requirement already satisfied: send2trash>=1.8.2 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.8.3)
Requirement already satisfied: terminado>=0.8.3 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.18.1)
Requirement already satisfied: websocket-client>=1.7 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.8.0)
Requirement already satisfied: babel>=2.10 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (2.17.0)
Requirement already satisfied: json5>=0.9.0 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (0.10.0)
Requirement already satisfied: jsonschema>=4.18.0 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (4.23.0)
Requirement already satisfied: requests>=2.31 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (2.32.3)
Requirement already satisfied: fastjsonschema>=2.15 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from nbformat>=5.7->nbconvert->jupyter) (2.21.1)
Requirement already satisfied: wcwidth in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets) (0.2.13)
Requirement already satisfied: soupsieve>1.2 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from beautifulsoup4->nbconvert->jupyter) (2.6)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from beautifulsoup4->nbconvert->jupyter) (4.13.0)
Requirement already satisfied: executing>=1.2.0 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from stack_data->ipython>=6.1.0->ipywidgets) (2.2.0)
Requirement already satisfied: asttokens>=2.1.0 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from stack_data->ipython>=6.1.0->ipywidgets) (3.0.0)
Requirement already satisfied: pure-eval in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from stack_data->ipython>=6.1.0->ipywidgets) (0.2.3)
Requirement already satisfied: sniffio>=1.1 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from anyio->httpx>=0.25.0->jupyterlab->jupyter) (1.3.1)
Requirement already satisfied: argon2-cffi-bindings in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (21.2.0)
Requirement already satisfied: attrs>=22.2.0 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (25.3.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (2024.10.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (0.36.2)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (0.24.0)
Requirement already satisfied: python-json-logger>=2.0.4 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (3.3.0)
Requirement already satisfied: pyyaml>=5.3 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (6.0.2)
Requirement already satisfied: rfc3339-validator in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.1.4)
Requirement already satisfied: rfc3986-validator>=0.1.1 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.1.1)
Requirement already satisfied: six>=1.5 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from python-dateutil>=2.8.2->jupyter-client>=6.1.12->ipykernel->jupyter) (1.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (3.4.1)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (2.3.0)
Requirement already satisfied: fqdn in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.5.1)
Requirement already satisfied: isoduration in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (20.11.0)
Requirement already satisfied: jsonpointer>1.13 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (3.0.0)
Requirement already satisfied: uri-template in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.3.0)
Requirement already satisfied: webcolors>=24.6.0 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (24.11.1)
Requirement already satisfied: cffi>=1.0.1 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.17.1)
Requirement already satisfied: pycparser in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (2.22)
Requirement already satisfied: arrow>=0.15.0 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.3.0)
Requirement already satisfied: types-python-dateutil>=2.8.10 in c:\users\sonum\onedrive\desktop\semantic book recommender\.venv\lib\site-packages (from arrow>=0.15.0->isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (2.9.0.20241206)
Note: you may need to restart the kernel to use updated packages.

In [18]:
pip show ipywidgets jupyter

Name: ipywidgets
Version: 8.1.5
Summary: Jupyter interactive widgets
Home-page: http://jupyter.org
Author: Jupyter Development Team
Author-email: jupyter@googlegroups.com
License: BSD 3-Clause License
Location: c:\Users\sonum\OneDrive\Desktop\semantic book recommender\.venv\Lib\site-packages
Requires: comm, ipython, jupyterlab-widgets, traitlets, widgetsnbextension
Required-by: jupyter
---
Name: jupyter
Version: 1.1.1
Summary: Jupyter metapackage. Install all the Jupyter components in one go.
Home-page: https://jupyter.org
Author: Jupyter Development Team
Author-email: jupyter@googlegroups.org
License: BSD
Location: c:\Users\sonum\OneDrive\Desktop\semantic book recommender\.venv\Lib\site-packages
Requires: ipykernel, ipywidgets, jupyter-console, jupyterlab, nbconvert, notebook
Required-by:
Note: you may need to restart the kernel to use updated packages.

In [19]:
db_books = FAISS.from_documents(documents, embedding=embeddings)

In [20]:
query = "a book about pyramids"
docs = db_books.similarity_search(query, k = 10)
docs

[Document(id='d1f18784-5faa-4260-a6cd-e20164455cae', metadata={'source': 'tagged_description.txt'}, page_content='"9780517884546 Drawing on more than a decade of research, this eye-opening account of one of the great mysteries of the ancient world links the construction of the pyramids and Egyptian religion to precise astronomical study. TV tie-in. 20,000 first printing."'),
 Document(id='27b07c30-f43d-47a1-a872-8a8e31dd32fe', metadata={'source': 'tagged_description.txt'}, page_content='"9780715633991 The New York Times Bestseller Arrives In The UK; The Egyptologist is a witty, inventive, brilliantly constructed novel about an archaeologist obsessed with finding the tomb of an apocryphal king. This darkly comic labyrinth of a story opens on the desert plains of Egypt in 1922, then winds its way from the slums of Australia to the ballrooms of Boston by way of Oxford, the battlefields of the First World War, and a royal court in turmoil. Exploring issues of class, greed, ambition, and the very human hunger for eternal life, The Egyptologist is a triumph of narrative bravado."'),
 Document(id='3ccde4b4-6acf-455d-ad07-9e6a26683c6c', metadata={'source': 'tagged_description.txt'}, page_content='"9780963188922 During WWII there was an attempt to achieve invisibility called the Philadelphia Experiment. Afterward occurred the now famous time travel experiments named after the underground base at Montauk Point on Long Island. Now this third book in the Montauk series summarises the events of the first two books and then takes the reader on an even more spectacular journey. The discovery of ancient pyramids at Montauk leads to a connection with Ancient Egypt and its position as a gateway to other dimensions. Like a psychic detective story beyond the occult, venture into an unprecedented investigation of the mystery schools of the earth and their connection to Egypt, Atlantis, Mars and the star Sirius. Chapters on new psychotronic weapons, the history of Mars, the strange death of Ian Fleming in connection with the Philadelphia Experiment, underground at the Montauk Base."'),
 Document(id='3c8f0898-18c7-44a1-a0be-a43a68940bdd', metadata={'source': 'tagged_description.txt'}, page_content='"9780192803467 Egyptian myths articulated the core values of one of the longest lasting civilizations in history, and myths of deities such as Isis and Osiris influenced contemporary cultures and became part of the Western cultural heritage. Egyptian Mythology: A Very Short Introduction explains the cultural and historical background to the fascinating and complex world of Egyptian myth, with each chapter dealing with a particular theme. To show the variety of source material for Egyptian myth, each chapter features a particular object--such as the obelisk known as Cleopatra\'s Needle, a golden statue of Tutankhamun, and a papyrus containing a story in which the Egyptian gods behave outrageously--which is illustrated by a photograph or line-drawing. The myth ""The Contendings of Horus and Seth"" is looked at in detail, and the many interpretations it has provoked are examined. In addition to a list of major deities and myths, there are explanations of related topics such as how hieroglyphs work, royal names and titles, and the Egyptian cosmos. There is also a timeline of Egyptian history, a glossary of technical terms and an up-to-date bibliography."'),
 Document(id='cadece07-40e1-4bb4-83df-fb3817ab9e21', metadata={'source': 'tagged_description.txt'}, page_content='"9780451207791 While Rommel\'s army bears down on Cairo, a ruthless Nazi agent called ""The Sphinx"" prowls the city\'s ancient streets to pave the way for an invasion, with no one to stand in his way but a luckless British officer and a Jewish girl, in the classic suspense novel of World War II. Reprint."'),
 Document(id='7d270d31-1b26-4fc6-a558-2495fa30cb22', metadata={'source': 'tagged_description.txt'}, page_content='"9780486274287 First paperbound edition of 485 remarkable plates (over 2,000 illustrations) that accompanied landmark work of the Enlightenment. Sharply detailed royalty-free images depict agriculture, military science, metalwork, mining, textile manufacture, masonry, carpentry, much more. Invaluable resource for art and craft use. Introduction and detailed captions by Charles C. Gillispie. Bibliography."'),
 Document(id='b46b41bc-674d-4e12-aaa4-8b4097ffecd9', metadata={'source': 'tagged_description.txt'}, page_content='"9780192840943 This is a book about the invention of Western philosophy, and the first thinkers to explore ideas about the nature of reality, time, and the origin of the universe. It begins with the finding of the new papyrus fragment of Empedocles\' poem, and uses the story of its discovery and interpretation to highlight the way our understanding of early philosophers is marked by their presentation in later sources. Generations of philosophers, both ancient and modern, have traced their inspiration back to the presocratics, even though we have very few of their writings left. In this book, Catherine Osborne invites her readers to dip their toes into the fragmentary remains of thinkers from Thales to Pythagoras, Heraclitus to Protagoras, to try to fill in the bits of a jigsaw that has been rejigged many times and in many different ways. ABOUT THE SERIES: The Very Short Introductions series from Oxford University Press contains hundreds of titles in almost every subject area. These pocket-sized books are the perfect way to get ahead in a new subject quickly. Our expert authors combine facts, analysis, perspective, new ideas, and enthusiasm to make interesting and challenging topics highly readable."'),
 Document(id='f94f83a4-8e16-434f-9d67-110d71ab5b80', metadata={'source': 'tagged_description.txt'}, page_content='"9780446518628 You have never read a book like this before -- a book that comes along once in a lifetime to change lives forever. In the rain forests of Peru, an ancient manuscript has been discovered. Within its pages are 9 key insights into life itself -- insights each human being is predicted to grasp sequentially; one insight, then another, as we move toward a completely spiritual culture on Earth. Drawing on ancient wisdom, it tells you how to make connections among the events happening in your life right now and lets you see what is going to happen to you in the years to come. The story it tells is a gripping one of adventure and discovery, but it is also a guidebook that has the power to crystallize your perceptions of why you are where you are in life and to direct your steps with a new energy and optimisim as you head into tomorrow."'),
 Document(id='8252429f-620f-4f80-82e7-dc22b2d25ad6', metadata={'source': 'tagged_description.txt'}, page_content='"9780870610639 Creating a summary of all human knowledge may not be the sort of undertaking we begin in the twenty-first century, but there is still room on our bookshelves for a classic--Summa Theologica, one of the world\'s oldest and greatest masterpieces. St. Thomas Aquinas has much to teach us--most especially how to confront the classic questions that are still with us after centuries of thought."'),
 Document(id='74250bc2-9395-4463-97d3-b383bac1101d', metadata={'source': 'tagged_description.txt'}, page_content='"9780156032391 A collection of essays and addresses includes the author\'s musings on Ptolemy, his reflections on the experimental writings of Borges and Joyce, and confessions about his own ambitions and anxieties. By the author of The Name of the Rose. Reprint."')]

In [24]:
# Extract the first word from the page content and strip any leading/trailing whitespace
isbn_str = docs[0].page_content.split()[0].strip()

# Remove any non-numeric characters from the string
isbn_str = ''.join(filter(str.isdigit, isbn_str))

# Convert the cleaned string to an integer
isbn_int = int(isbn_str)

# Now use isbn_int in your comparison
books[books["isbn13"] == isbn_int]

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
2576,9780517884546,0517884542,The Orion Mystery,Robert Bauval,History,http://books.google.com/books/content?id=XLSer...,"Drawing on more than a decade of research, thi...",1994.0,3.93,352.0,1076.0,The Orion Mystery: Unlocking the Secrets of th...,9780517884546 Drawing on more than a decade of...

In [22]:
def retrieve_semantic_recommendations(
        query: str,
        top_k: int = 10,
) -> pd.DataFrame:
    recs = db_books.similarity_search(query, k = 50)

    books_list = []

    for i in range(0, len(recs)):
        books_list += [int(recs[i].page_content.strip('"').split()[0])]

    return books[books["isbn13"].isin(books_list)]

In [23]:
retrieve_semantic_recommendations("A book about monster")

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
418,9780064407311,0064407314,Monster,Walter Dean Myers,Juvenile Fiction,http://books.google.com/books/content?id=se3Bu...,FADE IN: INTERIOR: Early morning in CELL BLOCK...,2001.0,3.71,281.0,53833.0,Monster,9780064407311 FADE IN: INTERIOR: Early morning...
648,9780140430363,0140430369,Three Gothic Novels,Horace Walpole;William Beckford;Mary Shelley,Fiction,http://books.google.com/books/content?id=ZjI_D...,"Walpole's The Castle of Otranto, Beckford's Va...",1968.0,3.70,505.0,290.0,Three Gothic Novels,"9780140430363 Walpole's The Castle of Otranto,..."
821,9780142407226,0142407224,The Tough Guide to Fantasyland,Diana Wynne Jones,Juvenile Nonfiction,http://books.google.com/books/content?id=v5jxA...,A unique guide to fantasy literature helps rea...,2006.0,3.94,234.0,3897.0,The Tough Guide to Fantasyland,9780142407226 A unique guide to fantasy litera...
874,9780143039938,0143039938,The Book of Imaginary Beings,Jorge Luis Borges;Margarita Guerrero;Andrew Hu...,Fiction,http://books.google.com/books/content?id=FuNQP...,A whimsical compendium of mythological creatur...,2006.0,4.09,236.0,4809.0,The Book of Imaginary Beings,9780143039938 A whimsical compendium of mythol...
886,9780152758516,0152758518,The Sleeping Giant and Other Stories,Eleanor Estes,Folklore,NaN,Three short tall tales : The sleeping giant --...,1948.0,4.00,101.0,10.0,The Sleeping Giant and Other Stories,9780152758516 Three short tall tales : The sle...
956,9780192823311,0192823310,Four Gothic Novels,Horace Walpole;William Beckford;Matthew Lewis;...,NaN,http://books.google.com/books/content?id=dADYA...,"Macabre and melodramatic, set in haunted castl...",1994.0,3.95,624.0,143.0,Four Gothic Novels: The Castle of Otranto; Vat...,"9780192823311 Macabre and melodramatic, set in..."
1074,9780237525378,0237525372,Oliver Twist,Pauline Francis;Charles Dickens,Juvenile Nonfiction,http://books.google.com/books/content?id=X6RvT...,This wonderful series is a quick way into a ra...,2003.0,3.66,48.0,92.0,Oliver Twist,9780237525378 This wonderful series is a quick...
1272,9780312853020,0312853025,"The Demon Princes, Vol. 1",Jack Vance,Fiction,http://books.google.com/books/content?id=L2nkD...,Collects three of the author's novels about th...,1997.0,4.25,446.0,1109.0,"The Demon Princes, Vol. 1: The Star King * The...",9780312853020 Collects three of the author's n...
1275,9780312862176,0312862172,The Dark Descent,Clive Barker;Ray Bradbury,Fiction,http://books.google.com/books/content?id=pNgZx...,Traces the evolution of the horror story by pr...,1997.0,4.26,1011.0,1959.0,The Dark Descent,9780312862176 Traces the evolution of the horr...
1277,9780312865764,0312865767,"The Demon Princes, Vol. 2",Jack Vance,Fiction,http://books.google.com/books/content?id=z3Uwc...,Jack Vance is undoubtedly one of the most gift...,1997.0,4.30,397.0,641.0,"The Demon Princes, Vol. 2: The Face * The Book...",9780312865764 Jack Vance is undoubtedly one of...
1374,9780321399533,0321399536,"Mary Wollstonecraft Shelley's Frankenstein, or...",Mary Wollstonecraft Shelley;Susan J. Wolfson,Fiction,http://books.google.com/books/content?id=9DcrA...,"From the Longman Cultural Editions series, thi...",2007.0,3.78,431.0,226.0,"Mary Wollstonecraft Shelley's Frankenstein, or...",9780321399533 From the Longman Cultural Editio...
1759,9780380720866,0380720868,Shadow of a Dark Queen,Raymond E. Feist,Fiction,http://books.google.com/books/content?id=j5Yyl...,A dread darkness is descending upon a great la...,1995.0,4.04,497.0,22935.0,Shadow of a Dark Queen: Book One of the Serpen...,9780380720866 A dread darkness is descending u...
1796,9780385129916,0385129912,Night Shift,Stephen King,Fiction,http://books.google.com/books/content?id=sl3DF...,More than twenty-five stories of horror and ni...,1978.0,3.99,344.0,470.0,Night Shift,9780385129916 More than twenty-five stories of...
1954,9780394536491,0394536495,The Castle in the Forest,Norman Mailer,Fiction,http://books.google.com/books/content?id=gsFmA...,A mysterious SS man offers an insightful glimp...,2007.0,3.13,477.0,2258.0,The Castle in the Forest: A Novel,9780394536491 A mysterious SS man offers an in...
2024,9780425181607,042518160X,Stephen King's Danse Macabre,Stephen King,Fiction,http://books.google.com/books/content?id=HxuOP...,The best-selling author offers a subjective to...,2001.0,3.63,400.0,20474.0,Stephen King's Danse Macabre,9780425181607 The best-selling author offers a...
2070,9780425208915,0425208915,Goddess of the Rose,P. C. Cast,Fiction,http://books.google.com/books/content?id=2RLPA...,This fourth novel in Cast's Goddess Summoning ...,2006.0,4.14,345.0,5367.0,Goddess of the Rose,9780425208915 This fourth novel in Cast's Godd...
2093,9780434009053,0434009059,The Hannibal Lecter Trilogy,Thomas Harris,"Lecter, Hannibal (Fictitious character)",http://books.google.com/books/content?id=rsmgQ...,"Red Dragon, The Silence of the Lambs and Hanni...",2001.0,4.42,1222.0,789.0,The Hannibal Lecter Trilogy,"9780434009053 Red Dragon, The Silence of the L..."
2224,9780441005833,0441005837,Rose Daughter,Robin McKinley,Juvenile Fiction,http://books.google.com/books/content?id=RtiQP...,The winner of the Newbery Award for The Hero a...,1998.0,3.77,304.0,16756.0,Rose Daughter,9780441005833 The winner of the Newbery Award ...
2259,9780446390576,0446390577,Bare Bones,Stephen King;Tim Underwood,Fiction,http://books.google.com/books/content?id=9GJAP...,"In a series of interviews, the acknowledged ma...",1989.0,4.16,224.0,3050.0,Bare Bones: Conversations on Terror with Steph...,"9780446390576 In a series of interviews, the a..."
2356,9780451170118,0451170113,Night Shift,Stephen King,Fiction,http://books.google.com/books/content?id=jIQL9...,Twenty stories of horror and nightmarish fanta...,1978.0,3.99,326.0,1273.0,Night Shift,9780451170118 Twenty stories of horror and nig...
2388,9780451218049,0451218043,Lover Eternal,J. R. Ward,Fiction,http://books.google.com/books/content?id=5tyYD...,"Fierce warrior and legendary lover, Rhage, a v...",2006.0,4.35,441.0,152091.0,Lover Eternal: A Novel of the Black Dagger Bro...,9780451218049 Fierce warrior and legendary lov...
2510,9780486297163,0486297160,Best Ghost and Horror Stories,Bram Stoker;Richard Dalby;Stefan R. Dziemianow...,Fiction,http://books.google.com/books/content?id=iiaFD...,Superb selection of 14 spine-tingling stories ...,1997.0,3.49,272.0,54.0,Best Ghost and Horror Stories,9780486297163 Superb selection of 14 spine-tin...
2750,9780553576375,0553576372,The Memoirs of Elizabeth Frankenstein,Theodore Roszak,Fiction,http://books.google.com/books/content?id=NDS1z...,"The passionate story of Elizabeth Lavenza, a g...",1996.0,3.55,440.0,223.0,The Memoirs of Elizabeth Frankenstein,9780553576375 The passionate story of Elizabet...
2846,9780575075825,0575075821,Grendel,John Gardner,Beowulf,http://books.google.com/books/content?id=yHfCH...,When Grendel is drawn up from the caves under ...,2004.0,3.69,144.0,221.0,Grendel,9780575075825 When Grendel is drawn up from th...
2871,9780590975001,0590975005,The BFG,Roald Dahl,Dreams,http://books.google.com/books/content?id=Az9hb...,Summary: Kidnapped from her orphanage by a BFG...,1982.0,4.22,207.0,99.0,The BFG,9780590975001 Summary: Kidnapped from her orph...
2984,9780671039745,0671039741,Salem's Lot,Stephen King,Fiction,http://books.google.com/books/content?id=ZZ-fP...,"In a classic tale of horror by Stephen King, a...",1999.0,4.01,631.0,3386.0,Salem's Lot,9780671039745 In a classic tale of horror by S...
3008,9780671731427,0671731424,Wolf's Hour,Robert McCammon,Fiction,http://books.google.com/books/content?id=p6rfb...,This book is a remarkable tale of pulse-poundi...,1990.0,4.05,603.0,8478.0,Wolf's Hour,9780671731427 This book is a remarkable tale o...
3261,9780722533949,0722533942,The Valkyries,Paulo Coelho,Angels,http://books.google.com/books/content?id=89VH5...,The author was instructed by his mysterious sp...,1996.0,3.31,243.0,16151.0,The Valkyries,9780722533949 The author was instructed by his...
3333,9780743255783,074325578X,Frankenstein,Mary Wollstonecraft Shelley,Fiction,http://books.google.com/books/content?id=OB6cY...,The story of Dr. Frankenstein and the obsessiv...,2003.0,3.78,448.0,18.0,Frankenstein: A Kaplan SAT Score-Raising Classic,9780743255783 The story of Dr. Frankenstein an...
3408,9780743471329,0743471326,Diablo: Moon of the Spider,Richard A. Knaak,Fiction,http://books.google.com/books/content?id=GcY6P...,"Since the beginning of time, the angelic hosts...",2006.0,3.95,336.0,722.0,Diablo: Moon of the Spider,"9780743471329 Since the beginning of time, the..."
3410,9780743477369,0743477367,Dracula,Bram Stoker,Fiction,http://books.google.com/books/content?id=7jnX3...,A new edition of the classic horror novel feat...,2003.0,3.99,528.0,9584.0,Dracula,9780743477369 A new edition of the classic hor...
3494,9780751504385,0751504386,Skeleton Crew,Stephen King,English fiction,http://books.google.com/books/content?id=WcrCQ...,Unrivalled monarch of the macabre Stephen King...,1993.0,3.95,612.0,93593.0,Skeleton Crew,9780751504385 Unrivalled monarch of the macabr...
3664,9780765354952,0765354950,Reliquary,Douglas Preston;Preston Douglas;Lincoln Child,Fiction,http://books.google.com/books/content?id=1OrPN...,Lieutenant D'Agosta of the New York police and...,2005.0,4.02,464.0,30514.0,Reliquary,9780765354952 Lieutenant D'Agosta of the New Y...
3780,9780786928576,0786928573,The Day of the Tempest,Jean Rabe,Fiction,http://books.google.com/books/content?id=hihCP...,As the evil dragon overlords lay waste to once...,2002.0,3.65,352.0,1337.0,The Day of the Tempest,9780786928576 As the evil dragon overlords lay...
3783,9780786931934,0786931930,The Search for Power,Margaret Weis,Fiction,http://books.google.com/books/content?id=zdriH...,An anthology of short fiction captures the wor...,2004.0,3.97,335.0,287.0,The Search for Power: Dragons of the War of Souls,9780786931934 An anthology of short fiction ca...
3798,9780791070482,0791070484,Bram Stoker's Dracula,Harold Bloom,Juvenile Nonfiction,http://books.google.com/books/content?id=vQ6SQ...,Presents a collection of critical essays on Br...,2003.0,3.83,243.0,6.0,Bram Stoker's Dracula,9780791070482 Presents a collection of critica...
3913,9780809530953,0809530953,Manna from Heaven,Roger Zelazny;Steven Brust;Scott Zrubeck,Fiction,http://books.google.com/books/content?id=GhIRP...,This new collection includes all five previous...,2003.0,3.95,255.0,334.0,Manna from Heaven,9780809530953 This new collection includes all...
3953,9780812509663,0812509668,The Medusa in the Shield,David G. Hartwell,Fiction,NaN,Includes an essay on the fiction of horror and...,1991.0,3.98,498.0,48.0,The Medusa in the Shield,9780812509663 Includes an essay on the fiction...
3954,9780812509670,0812509676,A Fabulous Formless Darkness,David G. Hartwell,Fiction,NaN,Originally published as part of The Dark Desce...,1992.0,4.21,608.0,33.0,A Fabulous Formless Darkness,9780812509670 Originally published as part of ...
3987,9780812927313,0812927311,The Little Baby Snoogle-Fleejer,Jimmy Carter,Friendship,http://books.google.com/books/content?id=lxtYS...,Teased by his friends because of his inability...,1995.0,3.19,24.0,42.0,The Little Baby Snoogle-Fleejer,9780812927313 Teased by his friends because of...
4141,9780859653725,0859653722,Dissecting Marilyn Manson,Gavin Baddeley,Music,http://books.google.com/books/content?id=7_FrA...,Marilyn Manson in more than a mere rock star -...,2005.0,3.86,192.0,504.0,Dissecting Marilyn Manson,9780859653725 Marilyn Manson in more than a me...
4403,9781400096220,1400096227,Beowulf,Howell D. Chickering,Literary Criticism,http://books.google.com/books/content?id=Yh_Uw...,A bilingual edition of the Old English epic po...,2006.0,3.43,464.0,233.0,Beowulf: A Dual-language Edition,9781400096220 A bilingual edition of the Old E...
4602,9781560258506,1560258500,Monster Island,David Wellington,Fiction,http://books.google.com/books/content?id=Bpsmi...,It's one month after a global disaster. Manhat...,2006.0,3.60,282.0,9635.0,Monster Island: A Zombie Novel,9781560258506 It's one month after a global di...
4662,9781568821405,1568821409,Miskatonic University,Sam Johnson,Games,http://books.google.com/books/content?id=kySWA...,"A sourcebook detailing the campus, courses, st...",2005.0,4.15,242.0,36.0,Miskatonic University: A Handbook to the Pride...,9781568821405 A sourcebook detailing the campu...
4664,9781568821481,1568821484,Call of Cthulhu RPG,Sandy Petersen;Lynn Willis,Games,http://books.google.com/books/content?id=Db4GA...,Ordinary people are confronted by the terrifyi...,2000.0,4.45,288.0,30.0,Call of Cthulhu RPG: Horror Roleplaying,9781568821481 Ordinary people are confronted b...
4716,9781577312093,1577312090,The Inner Reaches of Outer Space,Joseph Campbell,Religion,http://books.google.com/books/content?id=5VOGA...,Created from a powerful set of lectures delive...,2002.0,4.22,160.0,943.0,The Inner Reaches of Outer Space: Metaphor as ...,9781577312093 Created from a powerful set of l...
4803,9781586633578,1586633570,Frankenstein,Mary Shelley,LITERARY CRITICISM,http://books.google.com/books/content?id=1ToTg...,A guide to studying British author Mary Shelle...,2002.0,3.47,72.0,16.0,Frankenstein: Mary Shelley,9781586633578 A guide to studying British auth...
4919,9781595820129,1595820124,Vampire Hunter D Volume 1,Hideyuki Kikuchi;Yoshitaka Amano;Kevin Leahy,Comics & Graphic Novels,http://books.google.com/books/content?id=6Gswx...,"12,090 A.D. It is a dark time for the world. H...",2005.0,3.98,238.0,3782.0,Vampire Hunter D Volume 1,"9781595820129 12,090 A.D. It is a dark time fo..."
4944,9781600100291,1600100295,The Great and Secret Show,Chris Ryall,Comics & Graphic Novels,http://books.google.com/books/content?id=XA5AZ...,The beginning of a battle between good and evi...,2006.0,4.22,136.0,17047.0,The Great and Secret Show,9781600100291 The beginning of a battle betwee...
5166,9781932796780,1932796789,Dragons of Winter Night,Margaret Weis;Tracy Hickman;Andrew Dabb,Comics & Graphic Novels,http://books.google.com/books/content?id=92L9u...,"When dragons invade the land, a small band of ...",2007.0,4.14,358.0,33846.0,Dragons of Winter Night,"9781932796780 When dragons invade the land, a ..."